// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLExCnOXyAazJBfmTUWkB4KdcWA2vPpaA',
    appId: '1:357252290298:web:09fc88f32f813f19e89b43',
    messagingSenderId: '357252290298',
    projectId: 'health-project-4a71d',
    authDomain: 'health-project-4a71d.firebaseapp.com',
    storageBucket: 'health-project-4a71d.firebasestorage.app',
    measurementId: 'G-33CN7EHX64',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYIysZtPTDp27Khn8UpgUABpTP4OxIveM',
    appId: '1:357252290298:ios:605a52127a13d00ee89b43',
    messagingSenderId: '357252290298',
    projectId: 'health-project-4a71d',
    storageBucket: 'health-project-4a71d.firebasestorage.app',
    iosBundleId: 'com.example.patientApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn8BeIMRu2gcWya-7i81mGHo_btFFg954',
    appId: '1:357252290298:web:914ec98160b8544ae89b43',
    messagingSenderId: '357252290298',
    projectId: 'health-project-4a71d',
    authDomain: 'health-project-4a71d.firebaseapp.com',
    storageBucket: 'health-project-4a71d.firebasestorage.app',
    measurementId: 'G-JXJ34VBV5B',
  );

}